name: lockin_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0' # Perbarui ke rentang yang mendukung null safety dan kompatibel dengan Dart 3.9.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2 # Sudah mendukung null safety
  http: ^1.2.0 # Perbarui ke versi terbaru
  permission_handler: ^11.3.1 # Sudah mendukung null safety
  flutter_local_notifications: ^17.2.2 # Sudah mendukung null safety
  
  # Perbarui ke versi terbaru Firebase
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.0
  
  connectivity_plus: ^5.0.2 # Sudah mendukung null safety
  cupertino_icons: ^1.0.8 # Sudah mendukung null safety
  intl: ^0.20.2 # Sudah mendukung null safety

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0 # Sudah mendukung null safety

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/puzzle.png
    - assets/goal.png
    - assets/living.png
    - assets/google.png
    - assets/perempuan.png
    - assets/toa.png
    - assets/toggle_todolist.png
    - assets/toggle_journal.png
  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/GeneralSans-Regular.otf
        - asset: assets/fonts/GeneralSans-Bold.otf
          weight: 700
        - asset: assets/fonts/GeneralSans-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/GeneralSans-Extralight.otf
          weight: 200
        - asset: assets/fonts/GeneralSans-ExtralightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/GeneralSans-Italic.otf
          style: italic
        - asset: assets/fonts/GeneralSans-Light.otf
          weight: 300
        - asset: assets/fonts/GeneralSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/GeneralSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/GeneralSans-Semibold.otf
          weight: 600
        - asset: assets/fonts/GeneralSans-SemiboldItalic.otf
          weight: 600
          style: italic