// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRdMTAKkKcNVbdkBO-nq79AlO63Oh5D70',
    appId: '1:237532529304:web:25feb6922f2f2e485706ed',
    messagingSenderId: '237532529304',
    projectId: 'lockin-app-c8df2',
    authDomain: 'lockin-app-c8df2.firebaseapp.com',
    storageBucket: 'lockin-app-c8df2.firebasestorage.app',
    measurementId: 'G-1EBGNP4681',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC42WRFOvbGOOoedE1C4PSoWkQYJq3eBGs',
    appId: '1:237532529304:android:596ce3621e6032295706ed',
    messagingSenderId: '237532529304',
    projectId: 'lockin-app-c8df2',
    storageBucket: 'lockin-app-c8df2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYERodLepieafDqa-HD1tZH4T-rEdRPos',
    appId: '1:237532529304:ios:d1ca15260a2931f25706ed',
    messagingSenderId: '237532529304',
    projectId: 'lockin-app-c8df2',
    storageBucket: 'lockin-app-c8df2.firebasestorage.app',
    iosBundleId: 'com.example.lockinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYERodLepieafDqa-HD1tZH4T-rEdRPos',
    appId: '1:237532529304:ios:d1ca15260a2931f25706ed',
    messagingSenderId: '237532529304',
    projectId: 'lockin-app-c8df2',
    storageBucket: 'lockin-app-c8df2.firebasestorage.app',
    iosBundleId: 'com.example.lockinApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRdMTAKkKcNVbdkBO-nq79AlO63Oh5D70',
    appId: '1:237532529304:web:7b4da95f993b49295706ed',
    messagingSenderId: '237532529304',
    projectId: 'lockin-app-c8df2',
    authDomain: 'lockin-app-c8df2.firebaseapp.com',
    storageBucket: 'lockin-app-c8df2.firebasestorage.app',
    measurementId: 'G-VVVNFYED11',
  );
}
